### ISSUE TITLE
can't edit anything in custom entity input

### ISSUE THREAD

**Issue by macrozone** [globocom/megadraft#188]
I have a form as custom entity input. But i can't focus any textfield in it.

I am not sure when this feature broken. I try to investigate

**Comment by vierno** [comment]
Fixed #192 , please re-open if I'm wrong.

**Comment by macrozone** [comment]
actually this is not fixed, but its weird.

I have a form as entity input, doing something in this form seems to trigger an event, so that the editor will update its editorState. I think it has something to do with focus issues

I try to do a short reproduction
